export const models = [
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    developer: 'Anthropic',
    access: 'Proprietary',
    aaScore: 61,
    aaUrl: 'https://artificialanalysis.ai/articles/opus-5',
    transparency: 'Categories only',
    corpus: 'Public internet; commercially licensed/non-public data; crowd-worker and opt-in user data; internally generated and synthetic material.',
    lineage: ['gpt-2', 'chatgpt-launch'],
    lineageNote: 'Decoder-only autoregressive pretraining with RLHF-style chat tuning; Anthropic has not disclosed dense-vs-MoE architecture.',
    evidenceNote: 'Anthropic discloses source categories, but not dataset names, document manifests, mixture weights, or a downloadable pretraining corpus.',
    primaryUrl: 'https://www.anthropic.com/system-cards',
    primaryLabel: 'Anthropic system cards',
    researchUrl: 'https://www.nber.org/papers/w33598',
    researchLabel: 'Books3 membership study',
    corpusUrl: null,
    bestFor: 'Highest aggregate intelligence and agentic knowledge work in the July 2026 Artificial Analysis snapshot.'
  },
  {
    id: 'gpt-5-6-sol',
    name: 'GPT-5.6 Sol',
    developer: 'OpenAI',
    access: 'Proprietary',
    aaScore: 59,
    aaUrl: 'https://artificialanalysis.ai/evaluations/artificial-analysis-intelligence-index',
    transparency: 'Categories only',
    corpus: 'Publicly available internet information; third-party partner data; material supplied or generated by users, trainers, and researchers; reinforcement-learning data.',
    lineage: ['gpt-2', 'chatgpt-launch'],
    lineageNote: 'Same lab’s direct decoder-only lineage from GPT-2 through ChatGPT; OpenAI has not disclosed GPT-5.6’s architecture.',
    evidenceNote: 'The system card names high-level sources and processing practices, but does not identify datasets, files, proportions, or release the corpus.',
    primaryUrl: 'https://deploymentsafety.openai.com/gpt-5-6',
    primaryLabel: 'GPT-5.6 system card',
    researchUrl: 'https://arxiv.org/abs/2305.00118',
    researchLabel: 'GPT book archaeology',
    corpusUrl: null,
    bestFor: 'Frontier reasoning, research, science, coding, and computer-use tasks when managed access is acceptable.'
  },
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    developer: 'Moonshot AI',
    access: 'Open weights · custom license',
    aaScore: 57,
    aaUrl: 'https://artificialanalysis.ai/models/kimi-k3',
    transparency: 'Categories only',
    corpus: 'Curated web text, code, mathematics and knowledge-rich text, plus image-text and document data for native multimodality.',
    lineage: ['gpt-2', 'chatgpt-launch', 'gshard'],
    lineageNote: 'The technical report confirms a mixture-of-experts design, continuing GShard’s MoE-and-sharding approach.',
    evidenceNote: 'The technical report documents domains and training methods, but the complete samples, source-file manifest, mixture weights, and reconstruction recipe are not released.',
    primaryUrl: 'https://github.com/MoonshotAI/Kimi-K3/blob/main/k3_tech_report.pdf',
    primaryLabel: 'Kimi K3 technical report',
    researchUrl: 'https://www.nature.com/articles/s41467-026-68862-x',
    researchLabel: 'Cross-model data audit method',
    corpusUrl: null,
    bestFor: 'Leading open-weight frontier capability, native vision, long context, coding, and agentic document work.'
  },
  {
    id: 'grok-4-5',
    name: 'Grok 4.5',
    developer: 'SpaceXAI',
    access: 'Proprietary',
    aaScore: 54,
    aaUrl: 'https://artificialanalysis.ai/leaderboards/models/',
    transparency: 'Minimal disclosure',
    corpus: 'Publicly available data, licensed material, internally generated data, and curated coding, science, engineering, and mathematics datasets.',
    lineage: ['gpt-2', 'chatgpt-launch'],
    lineageNote: 'xAI disclosed Grok-1 as mixture-of-experts, but Grok 4.5’s specific architecture has not been published.',
    evidenceNote: 'The model card and launch post give categories and a January 2026 cutoff, but no named corpus, file list, proportions, or dataset access.',
    primaryUrl: 'https://media.x.ai/v1/website/card-7f81d41b.pdf',
    primaryLabel: 'Grok 4.5 model card',
    researchUrl: 'https://aclanthology.org/2025.naacl-long.99/',
    researchLabel: 'Data-imprint identification paper',
    corpusUrl: null,
    bestFor: 'Engineering, coding, and agentic workflows; corpus-level provenance is not available.'
  },
  {
    id: 'glm-5-2',
    name: 'GLM-5.2',
    developer: 'Z.ai',
    access: 'Open weights · MIT',
    aaScore: 51,
    aaUrl: 'https://artificialanalysis.ai/models/glm-5-2/',
    transparency: 'Categories only',
    corpus: 'GLM-5 family pretraining at 28.5T tokens; multilingual web, code, mathematics, scientific and long-context/agent trajectory data with synthetic post-training data.',
    lineage: ['gpt-2', 'chatgpt-launch', 'gshard'],
    lineageNote: 'GLM moved to a mixture-of-experts design from GLM-4.5 onward, in GShard’s MoE lineage.',
    evidenceNote: 'Weights and a technical report are public, but the full training dataset, document manifest, exact mixture, and reconstruction pipeline are not.',
    primaryUrl: 'https://huggingface.co/zai-org/GLM-5.2',
    primaryLabel: 'GLM-5.2 model card',
    researchUrl: 'https://www.dataprovenance.org/',
    researchLabel: 'Data Provenance Explorer',
    corpusUrl: null,
    bestFor: 'Strongest MIT-licensed open-weight option in the June 2026 Artificial Analysis snapshot, especially for long-horizon coding.'
  },
  {
    id: 'gemini-3-1-pro',
    name: 'Gemini 3.1 Pro',
    developer: 'Google DeepMind',
    access: 'Proprietary',
    aaScore: null,
    aaUrl: 'https://artificialanalysis.ai/models',
    transparency: 'Categories only',
    corpus: 'Web documents, text, code, images, audio and video; downloadable public datasets; crawler data; licensed and controlled user data; workforce and synthetic data.',
    lineage: ['gpt-2', 'chatgpt-launch', 'lamda', 'palm'],
    lineageNote: 'Google names Gemini a direct successor to its LaMDA (dialogue) and PaLM (scale) lineage; MoE use in some variants is reported but not officially confirmed.',
    evidenceNote: 'Google provides unusually detailed source categories and processing notes, but no dataset names, source-file manifest, mixture weights, or corpus download.',
    primaryUrl: 'https://deepmind.google/models/model-cards/gemini-3-1-pro/',
    primaryLabel: 'Gemini 3.1 Pro model card',
    researchUrl: 'https://www.nber.org/papers/w33598',
    researchLabel: 'Books3 membership study',
    corpusUrl: null,
    bestFor: 'Long-context, native multimodal analysis and advanced reasoning when Google-managed access is acceptable.'
  },
  {
    id: 'deepseek-v4',
    name: 'DeepSeek V4 Pro',
    developer: 'DeepSeek',
    access: 'Open weights · MIT',
    aaScore: 44,
    aaUrl: 'https://artificialanalysis.ai/articles/glm-5-2-is-the-new-leading-open-weights-model-on-the-artificial-analysis-intelligence-index/',
    transparency: 'Categories only',
    corpus: 'Public internet and licensed data, with additional high-quality long-document material such as scientific papers, technical reports, code, and synthetic reasoning data.',
    lineage: ['gpt-2', 'chatgpt-launch', 'gshard'],
    lineageNote: 'DeepSeek’s published architecture is mixture-of-experts, in GShard’s MoE-and-sharding lineage.',
    evidenceNote: 'The report describes domains and curation priorities, but neither the complete corpus nor source-file manifest and mixture is available.',
    primaryUrl: 'https://www.deepseek.com/en/transparency/',
    primaryLabel: 'DeepSeek transparency center',
    researchUrl: 'https://www.nature.com/articles/s41467-026-68862-x',
    researchLabel: 'Cross-model data audit method',
    corpusUrl: null,
    bestFor: 'Very low-cost open-weight reasoning and long-document work when top aggregate capability is not required.'
  },
  {
    id: 'qwen-3-6',
    name: 'Qwen 3.6',
    developer: 'Alibaba Qwen',
    access: 'Open weights · Apache 2.0 variants',
    aaScore: null,
    aaUrl: 'https://artificialanalysis.ai/models',
    transparency: 'Categories only',
    corpus: 'Trillions of tokens spanning public internet, third-party non-public sources, contractor and labeler data, synthetic data, and text, image, video, and audio modalities.',
    lineage: ['gpt-2', 'chatgpt-launch', 'gshard'],
    lineageNote: 'The Qwen 3 family documents both dense and GShard-style MoE variants; Qwen 3.6’s specific configuration is not itemized.',
    evidenceNote: 'Qwen publishes a family-level data summary, not the dataset manifest, exact mixture, source files, or reproducible corpus for Qwen 3.6.',
    primaryUrl: 'https://qwen.ai/training-data-summary',
    primaryLabel: 'Qwen training-data summary',
    researchUrl: 'https://www.dataprovenance.org/',
    researchLabel: 'Data Provenance Explorer',
    corpusUrl: null,
    bestFor: 'Practical multilingual and multimodal open-weight deployment across a range of model sizes.'
  },
  {
    id: 'olmo-3',
    name: 'OLMo 3 32B Think',
    developer: 'Ai2',
    access: 'Open weights · Apache 2.0',
    aaScore: null,
    aaUrl: 'https://artificialanalysis.ai/models',
    transparency: 'Full corpus',
    corpus: 'Dolma 3: web pages, science PDFs, code, mathematics, encyclopedic text, books and instruction/reasoning mixtures; Dolci post-training datasets.',
    lineage: ['gpt-2'],
    lineageNote: 'Dense decoder-only, continuing GPT-2’s fully-open release model with a documented recipe in T5’s spirit of published data and code.',
    evidenceNote: 'Ai2 publishes the model flow: downloadable datasets and mixtures, training code, recipes, checkpoints, logs, and post-training data.',
    primaryUrl: 'https://huggingface.co/allenai/Olmo-3-1125-32B',
    primaryLabel: 'OLMo 3 model card',
    researchUrl: 'https://allenai.org/blog/olmo3',
    researchLabel: 'OLMo 3 release notes',
    corpusUrl: 'https://huggingface.co/allenai/collections',
    bestFor: 'Training-data provenance, reproducibility, data-mixture research, and output tracing with OLMoTrace.'
  },
  {
    id: 'apertus-1-5',
    name: 'Apertus 1.5 70B',
    developer: 'Swiss AI Initiative',
    access: 'Open weights · Apache 2.0',
    aaScore: null,
    aaUrl: 'https://artificialanalysis.ai/models',
    transparency: 'Full corpus',
    corpus: 'A 15T-token, public-data multilingual corpus covering 1,000+ languages, reconstructed using published source lists, filtering rules, opt-outs, and preprocessing scripts.',
    lineage: ['gpt-2'],
    lineageNote: 'Dense decoder-only with a fully reconstructable corpus, in GPT-2’s open-release spirit; its multilingual scale echoes GShard’s goals without using MoE.',
    evidenceNote: 'Apertus publishes weights, training and evaluation code, documentation, checkpoints, data composition, and scripts that reconstruct the pretraining corpus.',
    primaryUrl: 'https://apertus-ai.org/pages/documentation/',
    primaryLabel: 'Apertus documentation',
    researchUrl: 'https://spcl.inf.ethz.ch/Publications/.pdf/2026_acl_apertus.pdf',
    researchLabel: 'Apertus technical paper',
    corpusUrl: 'https://github.com/swiss-ai/pretrain-data',
    bestFor: 'Transparent multilingual and European/Swiss deployments where auditability and reconstructability matter.'
  }
];

export const foundationalModels = [
  {
    id: 'bert',
    name: 'BERT',
    developer: 'Google AI Language · 2018',
    year: '2018',
    scale: '340M parameters (BERT-Large), pretrained on BooksCorpus and English Wikipedia (~3.3B words) with masked-language and next-sentence objectives.',
    primaryUse: 'Bidirectional encoder representations fine-tuned for classification, named-entity recognition, and question answering.',
    now: 'Encoder-only pretraining it popularized still underlies most embedding and retrieval models used for search and RAG.',
    primaryUrl: 'https://arxiv.org/abs/1810.04805',
    primaryLabel: 'BERT paper'
  },
  {
    id: 'gpt-2',
    name: 'GPT-2',
    developer: 'OpenAI · 2019',
    year: '2019',
    scale: '1.5B parameters at full release, trained on WebText: ~8M documents (40GB) scraped from outbound Reddit links.',
    primaryUse: 'Autoregressive next-token prediction for open-ended text generation, demonstrated as a zero-shot multitask learner.',
    now: 'Established the decoder-only, scale-first recipe that GPT-3, ChatGPT, and later frontier chat models continued.',
    primaryUrl: 'https://openai.com/index/better-language-models/',
    primaryLabel: 'GPT-2 release post'
  },
  {
    id: 'xlnet',
    name: 'XLNet',
    developer: 'Carnegie Mellon University & Google Brain · 2019',
    year: '2019',
    scale: '~340M parameters (XLNet-Large), trained on BooksCorpus, Wikipedia, Giga5, ClueWeb, and Common Crawl (~33B words).',
    primaryUse: 'Permutation-based autoregressive pretraining that captures bidirectional context without BERT’s masking.',
    now: 'A research line largely absorbed into later encoder work; day-to-day use shifted to RoBERTa and T5-style models.',
    primaryUrl: 'https://arxiv.org/abs/1906.08237',
    primaryLabel: 'XLNet paper'
  },
  {
    id: 'roberta',
    name: 'RoBERTa',
    developer: 'Meta AI (Facebook AI Research) · 2019',
    year: '2019',
    scale: '355M parameters (RoBERTa-Large), trained on 160GB of text: BookCorpus+Wikipedia, CC-News, OpenWebText, and Stories.',
    primaryUse: 'A more heavily and longer-trained BERT recipe, tuned for text classification and named-entity recognition.',
    now: 'Remains a common lightweight baseline encoder for classification tasks where a full LLM is unnecessary.',
    primaryUrl: 'https://arxiv.org/abs/1907.11692',
    primaryLabel: 'RoBERTa paper'
  },
  {
    id: 't5',
    name: 'T5',
    developer: 'Google Research · 2019',
    year: '2019',
    scale: 'Up to 11B parameters, trained on C4 (Colossal Clean Crawled Corpus), ~750GB of filtered Common Crawl text.',
    primaryUse: 'Casts every NLP task — translation, summarization, classification — as text-to-text generation.',
    now: 'The text-to-text framing carried forward into instruction-tuned and multitask training used by current models.',
    primaryUrl: 'https://arxiv.org/abs/1910.10683',
    primaryLabel: 'T5 paper'
  },
  {
    id: 'gshard',
    name: 'GShard',
    developer: 'Google · 2020',
    year: '2020',
    scale: '600B-parameter sparsely-gated mixture-of-experts model for multilingual machine translation across 100+ languages.',
    primaryUse: 'A sharding and conditional-computation system for training multi-hundred-billion-parameter models efficiently.',
    now: 'Its MoE and sharding techniques are the direct ancestor of the mixture-of-experts designs in today’s largest open and closed models.',
    primaryUrl: 'https://arxiv.org/abs/2006.16668',
    primaryLabel: 'GShard paper'
  },
  {
    id: 'lamda',
    name: 'LaMDA',
    developer: 'Google · 2022',
    year: '2022',
    scale: '137B parameters, pretrained on 1.56T words (~570GB) of public dialogue data and web text.',
    primaryUse: 'A dialogue-specialized model tuned for open-domain conversational applications.',
    now: 'Never released standalone; its dialogue training informed Google’s subsequent Bard/Gemini assistant work.',
    primaryUrl: 'https://arxiv.org/abs/2201.08239',
    primaryLabel: 'LaMDA paper'
  },
  {
    id: 'palm',
    name: 'PaLM',
    developer: 'Google Research · 2022',
    year: '2022',
    scale: '540B parameters, trained on 780B tokens of multilingual web pages, books, Wikipedia, conversation, and code.',
    primaryUse: 'Demonstrated large-scale few-shot reasoning, code generation, and multilingual understanding via the Pathways system.',
    now: 'Superseded by Google’s Gemini family, which absorbed and extended its scaling and reasoning results.',
    primaryUrl: 'https://arxiv.org/abs/2204.02311',
    primaryLabel: 'PaLM paper'
  },
  {
    id: 'sparrow',
    name: 'Sparrow',
    developer: 'DeepMind · 2022',
    year: '2022',
    scale: 'Built on a 70B-parameter Chinchilla-family model, fine-tuned with RLHF plus rules and live Google Search evidence citation.',
    primaryUse: 'A research prototype dialogue agent studying helpfulness, correctness, and harm-reduction rules together.',
    now: 'Never publicly released; its rule-conditioned RLHF and evidence-citation approach fed into later Google/DeepMind assistant safety work.',
    primaryUrl: 'https://arxiv.org/abs/2209.14375',
    primaryLabel: 'Sparrow paper'
  },
  {
    id: 'chatgpt-launch',
    name: 'ChatGPT (initial release)',
    developer: 'OpenAI · 2022',
    year: '2022',
    scale: 'Built on a GPT-3.5-series model (~175B parameters), fine-tuned with instruction data and RLHF.',
    primaryUse: 'General-purpose conversational assistant covering language modeling, generation, sentiment analysis, and translation.',
    now: 'Superseded within OpenAI’s own lineup by GPT-4 and later models; see the current reference models above for today’s frontier.',
    primaryUrl: 'https://openai.com/index/chatgpt/',
    primaryLabel: 'ChatGPT launch post'
  }
];

const routes = {
  'knowledge-work': 'claude-opus-5',
  coding: 'claude-opus-5',
  provenance: 'olmo-3',
  'open-frontier': 'kimi-k3',
  'open-engineering': 'glm-5-2',
  multilingual: 'apertus-1-5',
  multimodal: 'gemini-3-1-pro',
  budget: 'deepseek-v4'
};

export const advisorChoices = [
  { priority: 'knowledge-work', icon: 'KW', label: 'Knowledge work', detail: 'Best overall' },
  { priority: 'coding', icon: 'CD', label: 'Agentic coding', detail: 'Build and debug' },
  { priority: 'provenance', icon: 'PR', label: 'Training provenance', detail: 'Inspectable corpus' },
  { priority: 'open-frontier', icon: 'OF', label: 'Open frontier', detail: 'Top open weights' },
  { priority: 'open-engineering', icon: 'EN', label: 'Open engineering', detail: 'MIT-licensed weights' },
  { priority: 'multilingual', icon: 'ML', label: 'Multilingual', detail: 'Transparent data' },
  { priority: 'multimodal', icon: 'MM', label: 'Multimodal', detail: 'Long context' },
  { priority: 'budget', icon: '$', label: 'Budget', detail: 'Capable and efficient' }
];

export function renderAdvisorChoices(activePriority = 'knowledge-work') {
  return advisorChoices.map((choice) => `
    <button class="advisor-choice${choice.priority === activePriority ? ' is-active' : ''}"
      type="button"
      data-priority="${choice.priority}"
      aria-pressed="${choice.priority === activePriority}">
      <span class="advisor-choice__icon" aria-hidden="true">${choice.icon}</span>
      <span>
        <strong>${choice.label}</strong>
        <small>${choice.detail}</small>
      </span>
    </button>
  `).join('');
}

export function recommendModel(priority) {
  const selectedId = routes[priority] ?? routes['knowledge-work'];
  return models.find((model) => model.id === selectedId);
}

const transparencyClasses = {
  'Full corpus': 'badge badge-full',
  'Categories only': 'badge badge-partial',
  'Minimal disclosure': 'badge badge-minimal'
};

function link(url, label) {
  return `<a href="${url}" target="_blank" rel="noreferrer">${label}<span aria-hidden="true"> ↗</span></a>`;
}

function renderModels() {
  const container = document.querySelector('#model-list');
  if (!container) return;

  container.innerHTML = models.map((model) => `
    <article class="model-card" data-model="${model.id}">
      <div class="model-card__top">
        <div>
          <p class="eyebrow">${model.developer}</p>
          <h3>${model.name}</h3>
        </div>
        <span class="${transparencyClasses[model.transparency]}">${model.transparency}</span>
      </div>
      <p class="access">${model.access}</p>
      <div class="score-row">
        <span>AA Intelligence Index</span>
        <strong>${model.aaScore ?? 'Not scored'}</strong>
      </div>
      <p class="corpus">${model.corpus}</p>
      <div class="lineage-row">
        <span class="lineage-label">Foundational lineage:</span>
        ${model.lineage.map((id) => {
          const ancestor = foundationalModels.find((foundational) => foundational.id === id);
          return ancestor ? `<a class="lineage-badge" href="#foundational-${ancestor.id}">${ancestor.name}</a>` : '';
        }).join('')}
      </div>
      <p class="lineage-note">${model.lineageNote}</p>
      <p class="evidence"><strong>Evidence boundary:</strong> ${model.evidenceNote}</p>
      <p class="best"><strong>Best fit:</strong> ${model.bestFor}</p>
      <div class="source-links">
        ${link(model.primaryUrl, model.primaryLabel)}
        ${model.corpusUrl ? link(model.corpusUrl, 'Corpus / reconstruction') : link(model.researchUrl, model.researchLabel)}
        ${link(model.aaUrl, 'Performance source')}
      </div>
    </article>
  `).join('');
}

function renderFoundational() {
  const container = document.querySelector('#foundational-list');
  if (!container) return;

  container.innerHTML = foundationalModels.map((model) => `
    <article class="legacy-card" id="foundational-${model.id}" data-model="${model.id}">
      <div class="legacy-card__top">
        <div>
          <p class="eyebrow">${model.developer}</p>
          <h3>${model.name}</h3>
        </div>
        <span class="legacy-year">${model.year}</span>
      </div>
      <p class="scale">${model.scale}</p>
      <p class="use"><strong>Built for:</strong> ${model.primaryUse}</p>
      <p class="now"><strong>Since then:</strong> ${model.now}</p>
      <div class="source-links">
        ${link(model.primaryUrl, model.primaryLabel)}
      </div>
    </article>
  `).join('');
}

function renderRecommendation(priority) {
  const result = recommendModel(priority);
  const container = document.querySelector('#advisor-result');
  if (!container) return;

  container.innerHTML = `
    <div>
      <p class="eyebrow">Recommended route</p>
      <h3>${result.name}</h3>
      <p>${result.bestFor}</p>
    </div>
    <div class="advisor-result__meta">
      <span class="${transparencyClasses[result.transparency]}">${result.transparency}</span>
      <span>AA score: <strong>${result.aaScore ?? 'not published'}</strong></span>
      ${link(result.primaryUrl, 'Review evidence')}
    </div>
  `;
}

if (typeof document !== 'undefined') {
  renderModels();
  renderFoundational();
  const advisor = document.querySelector('#advisor-priorities');
  if (advisor) {
    const selectPriority = (priority) => {
      renderRecommendation(priority);
      for (const button of advisor.querySelectorAll('.advisor-choice')) {
        const isActive = button.dataset.priority === priority;
        button.classList.toggle('is-active', isActive);
        button.setAttribute('aria-pressed', String(isActive));
      }
    };

    advisor.innerHTML = renderAdvisorChoices();
    advisor.addEventListener('click', (event) => {
      const button = event.target.closest('.advisor-choice');
      if (button) selectPriority(button.dataset.priority);
    });
    selectPriority('knowledge-work');
  }
}
